# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jonnii-yelp}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Josh Nichols"]
  s.date = %q{2010-09-08}
  s.description = %q{
The yelp rubygem provides a Ruby object-oriented interface to the Yelp 
REST API described in detail at:

http://www.yelp.com/developers/getting_started}
  s.email = %q{shaper@fatgoose.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
     "README.rdoc"
  ]
  s.files = [
    "CHANGELOG.rdoc",
     "LICENSE.txt",
     "Manifest.txt",
     "README.rdoc",
     "Rakefile",
     "TODO.txt",
     "lib/yelp.rb",
     "lib/yelp/client.rb",
     "lib/yelp/neighborhood/request/base.rb",
     "lib/yelp/neighborhood/request/geo_point.rb",
     "lib/yelp/neighborhood/request/location.rb",
     "lib/yelp/phone/request/number.rb",
     "lib/yelp/record.rb",
     "lib/yelp/request.rb",
     "lib/yelp/response_format.rb",
     "lib/yelp/review/request/base.rb",
     "lib/yelp/review/request/bounding_box.rb",
     "lib/yelp/review/request/geo_point.rb",
     "lib/yelp/review/request/location.rb",
     "test/test_client.rb",
     "test/test_neighborhood_search.rb",
     "test/test_phone_search.rb",
     "test/test_review_search.rb",
     "test/yelp_helper.rb"
  ]
  s.homepage = %q{http://rubyforge.org/projects/yelp}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{An object-oriented interface to the Yelp Developer API.}
  s.test_files = [
    "test/test_client.rb",
     "test/test_neighborhood_search.rb",
     "test/test_phone_search.rb",
     "test/test_review_search.rb",
     "test/yelp_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, [">= 1.1.1"])
    else
      s.add_dependency(%q<json>, [">= 1.1.1"])
    end
  else
    s.add_dependency(%q<json>, [">= 1.1.1"])
  end
end

